// SPDX-FileCopyrightText: 2026 Foundation Devices, Inc. <hello@foundation.xyz>
// SPDX-License-Identifier: MIT

use slint_keyos_platform_build::{compile_options, CompileOptions};

fn main() {
    // Themes are generated by the Foundation CLI and pulled in at compile time
    // via foundation_themes::include_theme! (see src/theme.rs).
    //
    // Resolve the generated-theme directory (the FOUNDATION_THEMES_RUST_DIR
    // override that `foundation build`/`sim` set, otherwise the default cache
    // location) and re-export it through cargo:rustc-env so the include_theme!
    // env!() always sees it, independent of how the ambient build environment
    // is set up.
    let themes_rust_dir = std::env::var("FOUNDATION_THEMES_RUST_DIR").unwrap_or_else(|_| {
        let home = std::env::var("HOME").unwrap_or_else(|_| ".".to_string());
        format!("{home}/.foundation/themes/rust")
    });
    println!("cargo:rustc-env=FOUNDATION_THEMES_RUST_DIR={themes_rust_dir}");
    println!("cargo:rerun-if-env-changed=FOUNDATION_THEMES_RUST_DIR");

    compile_options(CompileOptions {
        module_path: "ui/app.slint",
        include_slint: true,
        include_router: false,
        include_translations: false,
        include_time_localization: false,
    });
}
